version: '3'

services:

  php:
    build: ./.docker/php
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - local_php_project
    working_dir: /app
    command: "php -S 0.0.0.0:8080"

  db:
    image: percona:ps-8.0.29-21
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - local_php_project
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password

volumes:
  mysqldata:

networks:
  local_php_project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28