version: '3'

services:

  php:
    build: ./.docker/php
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: "php -S 0.0.0.0:8080"

  db:
    image: percona:ps-8.0.29-21
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password